<?php

namespace Fire\Robo\Plugin\Commands;

use Robo\Exception\AbortTasksException;
use Robo\Symfony\ConsoleIO;
use Robo\Robo;
use Symfony\Component\Yaml\Yaml;

/**
 * Provides a command to initialize Playwright VRT.
 */
class VrtPlaywrightInitCommand extends FireCommandBase {

  /**
   * Configure Playwright VRT scaffolding using ATK.
   *
   * Usage Example: fire vrt:playwright:init
   *
   * @command vrt:playwright:init
   * @aliases vpinit
   * @option $y Run the command with no interection required.
   */
  public function vrtPlaywrightInit(ConsoleIO $io, $opts = ['y|y' => FALSE]) {
    $env = Robo::config()->get('local_environment');
    $projectRoot = $this->getLocalEnvRoot();
    $drupalRoot = $this->getDrupalRoot();
    $atkHome = getenv('ATK_HOME');
    if (!$atkHome) {
      throw new AbortTasksException('ATK_HOME is not set in your environment. Add `export ATK_HOME=./tests/playwright` to your shell profile (PATH) and rerun.');
    }
    $testsRoot = $this->resolveAtkHomePath($projectRoot, $atkHome);

    $shouldProceed = TRUE;
    if (!$opts['y']) {
      $shouldProceed = $io->confirm("This action will generate/update Playwright VRT scaffolding in $testsRoot. Continue?", TRUE);
    }
    if (!$shouldProceed) {
      $io->warning('Playwright VRT init skipped.');
      return 0;
    }
    $vrtEnv = $this->collectVrtEnvConfig($io, $projectRoot);
    //  $tasks = $this->collectionBuilder($io);
    $this->taskExec($env . " composer require 'drupal/automated_testing_kit' 'drupal/qa_accounts:^1.1'")->dir($projectRoot)->run();
    $atkSetup = $drupalRoot . '/modules/contrib/automated_testing_kit/module_support/atk_setup';
    if (!file_exists($atkSetup)) {
      throw new AbortTasksException("Automated Testing Kit not found at $atkSetup. Install drupal/automated_testing_kit and rerun.");
    }
    $this->taskFilesystemStack()->mkdir($projectRoot . '/' . $atkHome)->run();
    $atkCommand = $atkSetup . ' playwright';
    $this->taskExec($atkCommand)->dir($projectRoot)->run();
    $testsDir = $testsRoot . '/tests';
    // Removing not needed test files and folders generated by ATK, but
    // keeping support, data, and vrt folders if they exist.
    if (is_dir($testsDir)) {
      $testItems = glob($testsDir . '/*') ?: [];
      foreach ($testItems as $testItem) {
        if (is_dir($testItem)) {
          $folderName = basename($testItem);
          if (in_array($folderName, ['support', 'data', 'vrt'], TRUE)) {
            continue;
          }
          $this->taskFilesystemStack()->remove($testItem)->run();
        }
      }
    }
     // Enabing ATK and QA accounts modules in Drupal to ensure the test
     //environment is ready.
     $this->taskExec($env . ' drush en automated_testing_kit qa_accounts -y')->dir($projectRoot)->run();
    if (!is_dir($testsRoot . '/tests/vrt')) {
      $this->taskFilesystemStack()->mkdir($testsRoot . '/tests/vrt')->run();
    }
    if (!is_dir($testsRoot . '/tests/support')) {
      $this->taskFilesystemStack()->mkdir($testsRoot . '/tests/support')->run();
    }
    if (!is_dir($testsRoot . '/css')) {
      $this->taskFilesystemStack()->mkdir($testsRoot . '/css')->run();
    }

    $assets = dirname(__DIR__, 4) . '/assets/templates/playwright/';
    $this->taskFilesystemStack()->copy($assets . 'playwright.config.js', $testsRoot . '/playwright.config.js', TRUE)->run();
    $this->taskFilesystemStack()->copy($assets . 'playwright.atk.config.js', $testsRoot . '/playwright.atk.config.js', TRUE)->run();
    $this->taskFilesystemStack()->copy($assets . 'css/screenshotGlobalStyle.css', $testsRoot . '/css/screenshotGlobalStyle.css', TRUE)->run();
    $this->taskFilesystemStack()->copy($assets . 'tests/support/4k_utilities.js', $testsRoot . '/tests/support/4k_utilities.js', TRUE)->run();
    $this->taskFilesystemStack()->copy($assets . 'tests/vrt/common.spec.js', $testsRoot . '/tests/vrt/common.spec.js', TRUE)->run();
    $this->taskFilesystemStack()->copy($assets . 'data/vrtCommonPages.json', $testsRoot . '/tests/data/vrtCommonPages.json', TRUE)->run();
    $this->taskFilesystemStack()->copy($assets . '.nvmrc', $testsRoot . '/.nvmrc', TRUE)->run();

    $gitignorePath = $testsRoot . '/.gitignore';
    $gitignoreTask = $this->taskWriteToFile($gitignorePath);
    if (file_exists($gitignorePath)) {
      $gitignoreTask->textFromFile($gitignorePath);
    }
    $gitignoreTask
      ->appendUnlessMatches('/node_modules\//', "node_modules/\n")
      ->appendUnlessMatches('/\/test-results\//', "/test-results/\n")
      ->appendUnlessMatches('/\/playwright-report\//', "/playwright-report/\n")
      ->appendUnlessMatches('/\/blob-report\//', "/blob-report/\n")
      ->appendUnlessMatches('/\/cache\//', "/cache/\n")
      ->appendUnlessMatches('/\/\.auth\//', "/.auth/\n")
      ->appendUnlessMatches('/\/tests\/support\/loginAuth\.json/', "/tests/support/loginAuth.json\n")
      ->appendUnlessMatches('/\.env/', ".env\n")
      ->appendUnlessMatches('/\*\.spec\.js-snapshots/', "*.spec.js-snapshots\n");
    $gitignoreTask->run();
    $this->writeVrtEnvFile($testsRoot, $vrtEnv);

    // Updating npm packages and installing Playwright browsers && 4k vrt helper
    // package.
    $nvmDir = getenv('NVM_DIR');
    if ($nvmDir && file_exists($testsRoot . '/.nvmrc')) {
      $nvmScript = rtrim($nvmDir, '/') . '/nvm.sh';
      if (!file_exists($nvmScript)) {
        throw new AbortTasksException("NVM script not found at $nvmScript.");
      }

      $command = 'export NVM_DIR=' . escapeshellarg($nvmDir)
        . ' && . ' . escapeshellarg($nvmScript)
        . ' && cd ' . escapeshellarg($testsRoot)
        . ' && nvm install'
        . ' && npm install --no-audit --no-fund'
        . ' && npm install --no-audit --no-fund @fkbender/playwright-vrt-scripts'
        . ' && npx playwright install --with-deps';
      $this->taskExec($command)->run();
    }
    else {
      $this->taskExec($env . ' npm install')->dir($testsRoot)->run();
      $this->taskExec($env . ' npm install @fkbender/playwright-vrt-scripts')->dir($testsRoot)->run();
      $this->taskExec($env . ' npx playwright install --with-deps')->dir($testsRoot)->run();
    }
    $this->addVrtScriptsToPackageJson($testsRoot);

    $defaultBaseUrl = $this->getDefaultBaseUrl($projectRoot);

      $this->taskReplaceInFile($testsRoot . '/playwright.config.js')
        ->from('__DEFAULT_BASE_URL__')
        ->to($defaultBaseUrl)->run();

    $drushCmd = $this->getDefaultDrushCommand();
    $pantheonSite = Robo::config()->get('remote_sitename') ?: 'remote-pantheon-site-machine-name';

      $this->taskReplaceInFile($testsRoot . '/playwright.atk.config.js')
        ->from('__DRUSH_CMD__')
        ->to($drushCmd)->run();

      $this->taskReplaceInFile($testsRoot . '/playwright.atk.config.js')
        ->from('__PANTHEON_SITE__')
        ->to($pantheonSite)->run();
  }

  /**
   * Resolve ATK_HOME into an absolute path.
   */
  private function resolveAtkHomePath(string $projectRoot, string $atkHome) {
    $atkHome = trim($atkHome);
    if ($atkHome === '') {
      return $projectRoot . '/tests/playwright';
    }
    if (strpos($atkHome, '/') === 0) {
      return rtrim($atkHome, '/');
    }
    $relative = ltrim($atkHome, './');
    return rtrim($projectRoot, '/') . '/' . $relative;
  }

  /**
   * Collect values for the Playwright VRT .env file.
   */
  private function collectVrtEnvConfig(ConsoleIO $io, string $projectRoot) {
    $baselineTerminusEnv = Robo::config()->get('remote_canonical_env') ?: 'live';
    $baselineTerminusSite = Robo::config()->get('remote_sitename') ?: '';
    $baselineUrl = $this->getDefaultBaselineUrl($baselineTerminusEnv, $baselineTerminusSite);
    $candidateUrl = $this->getDefaultBaseUrl($projectRoot);

    $baselineUrl = $io->ask('Please enter the baseline Url', $baselineUrl);
    $baselineTerminusEnv = $io->ask('Please enter baseline Terminus env', $baselineTerminusEnv);
    $baselineTerminusSite = $io->ask('Please enter baseline Terminus Site', $baselineTerminusSite);
    $candidateUrl = $io->ask('Please enter The candidate url(local)', $candidateUrl);

    return [
      'baseline_url' => trim((string) $baselineUrl),
      'candidate_url' => trim((string) $candidateUrl),
      'baseline_terminus_env' => trim((string) $baselineTerminusEnv),
      'baseline_terminus_site' => trim((string) $baselineTerminusSite),
    ];
  }

  /**
   * Write Playwright VRT environment variables to tests/playwright/.env.
   */
  private function writeVrtEnvFile(string $testsRoot, array $vrtEnv) {
    $contents = implode("\n", [
      'BASELINE_URL="' . $this->escapeDotEnvDoubleQuotedValue($vrtEnv['baseline_url']) . '"',
      'CANDIDATE_URL="' . $this->escapeDotEnvDoubleQuotedValue($vrtEnv['candidate_url']) . '"',
      'BASELINE_TERMINUS_ENV=' . $vrtEnv['baseline_terminus_env'],
      'BASELINE_TERMINUS_SITE=' . $vrtEnv['baseline_terminus_site'],
    ]) . "\n";

    $this->taskWriteToFile($testsRoot . '/.env')
      ->text($contents)
      ->run();
  }

  /**
   * Escape a value for use in a double-quoted dotenv assignment.
   */
  private function escapeDotEnvDoubleQuotedValue(string $value) {
    return str_replace(
      ["\\", '"', "\n", "\r"],
      ["\\\\", '\\"', '\\n', ''],
      $value
    );
  }

  /**
   * Infer a baseline URL from remote Terminus config when available.
   */
  private function getDefaultBaselineUrl(string $baselineTerminusEnv, string $baselineTerminusSite) {
    if (Robo::config()->get('remote_platform') === 'pantheon' && $baselineTerminusEnv && $baselineTerminusSite) {
      return 'https://' . $baselineTerminusEnv . '-' . $baselineTerminusSite . '.pantheonsite.io';
    }

    return '';
  }

  /**
   * Infer the best default base URL from local env config.
   */
  private function getDefaultBaseUrl(string $projectRoot) {
    $defaultBaseUrl = 'http://mysite.site';
    $env = Robo::config()->get('local_environment');

    if ($env === 'lando' && file_exists($projectRoot . '/.lando.yml')) {
      $landoConfig = Yaml::parse(file_get_contents($projectRoot . '/.lando.yml'));
      if (isset($landoConfig['name'])) {
        return 'https://' . $landoConfig['name'] . '.lndo.site';
      }
    }

    if ($env === 'ddev' && file_exists($projectRoot . '/.ddev/config.yaml')) {
      $ddevConfig = Yaml::parse(file_get_contents($projectRoot . '/.ddev/config.yaml'));
      if (isset($ddevConfig['name'])) {
        return 'https://' . $ddevConfig['name'] . '.ddev.site';
      }
    }

    return $defaultBaseUrl;
  }

  /**
   * Determine the local drush command to use.
   */
  private function getDefaultDrushCommand() {
    $env = Robo::config()->get('local_environment');
    if ($env === 'lando') {
      return 'lando drush';
    }
    if ($env === 'ddev') {
      return 'ddev drush';
    }
    return 'drush';
  }

  /**
   * Add VRT npm scripts to the generated Playwright package.json.
   */
  private function addVrtScriptsToPackageJson(string $testsRoot) {
    $packageJsonPath = $testsRoot . '/package.json';
    if (!file_exists($packageJsonPath)) {
      throw new AbortTasksException("Package file not found at $packageJsonPath.");
    }

    $packageJson = json_decode(file_get_contents($packageJsonPath), TRUE);
    if (!is_array($packageJson)) {
      throw new AbortTasksException("Unable to parse $packageJsonPath.");
    }
    if (isset($packageJson['scripts']) && !is_array($packageJson['scripts'])) {
      throw new AbortTasksException("Invalid scripts section in $packageJsonPath.");
    }

    $packageJson['scripts'] = array_merge($packageJson['scripts'] ?? [], [
      'vrt' => 'playwright-vrt',
      'vrt:local' => 'playwright-vrt-local',
      'vrt:ci' => 'playwright-vrt-ci',
    ]);

    $packageJson = json_encode($packageJson, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    if ($packageJson === FALSE) {
      throw new AbortTasksException("Unable to encode $packageJsonPath.");
    }

    $this->taskWriteToFile($packageJsonPath)
      ->text($packageJson . "\n")
      ->run();
  }

}
